model_list:
  - model_name: cerebras-qwen-3-235b-a22b-instruct-2507
    litellm_params:
      model: openai/qwen-3-235b-a22b-instruct-2507
      api_base: https://api.cerebras.ai/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: cloudflare-gemini-flash-latest
    litellm_params:
      model: openai/gemini-flash-latest
      api_base: https://gemini-balance-do-cloudflare.lemonjia.workers.dev/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: cloudflare-gemini-flash-latest
    litellm_params:
      model: openai/gemini-flash-latest
      api_base: https://openai-gemini-cloudflare.lemonjia.workers.dev/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: cloudflare-gemini-flash-lite-latest
    litellm_params:
      model: openai/gemini-flash-lite-latest
      api_base: https://gemini-balance-do-cloudflare.lemonjia.workers.dev/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: cloudflare-gemini-flash-lite-latest
    litellm_params:
      model: openai/gemini-flash-lite-latest
      api_base: https://openai-gemini-cloudflare.lemonjia.workers.dev/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: cloudflare-gemini-pro-latest
    litellm_params:
      model: openai/gemini-pro-latest
      api_base: https://gemini-balance-do-cloudflare.lemonjia.workers.dev/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: ollama-cogito-2.1
    litellm_params:
      model: openai/cogito-2.1:671b-cloud
      api_base: https://ollama.com/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: ollama-deepseek-v3.1
    litellm_params:
      model: openai/deepseek-v3.1:671b-cloud
      api_base: https://ollama.com/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: ollama-gemini-3-pro-preview
    litellm_params:
      model: openai/gemini-3-pro-preview:latest
      api_base: https://ollama.com/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: ollama-gemma3
    litellm_params:
      model: openai/gemma3:27b-cloud
      api_base: https://ollama.com/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: ollama-glm-4.6
    litellm_params:
      model: openai/glm-4.6:cloud
      api_base: https://ollama.com/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: ollama-gpt-oss
    litellm_params:
      model: openai/gpt-oss:120b-cloud
      api_base: https://ollama.com/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: ollama-kimi-k2
    litellm_params:
      model: openai/kimi-k2:1t-cloud
      api_base: https://ollama.com/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: ollama-kimi-k2-thinking
    litellm_params:
      model: openai/kimi-k2-thinking:cloud
      api_base: https://ollama.com/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: ollama-minimax-m2
    litellm_params:
      model: openai/minimax-m2:cloud
      api_base: https://ollama.com/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: ollama-ministral-3
    litellm_params:
      model: openai/ministral-3:14b-cloud
      api_base: https://ollama.com/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: ollama-mistral-large-3
    litellm_params:
      model: openai/mistral-large-3:675b-cloud
      api_base: https://ollama.com/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: ollama-qwen3-coder
    litellm_params:
      model: openai/qwen3-coder:480b-cloud
      api_base: https://ollama.com/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: ollama-qwen3-vl
    litellm_params:
      model: openai/qwen3-vl:235b-cloud
      api_base: https://ollama.com/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: ollama-qwen3-vl-instruct
    litellm_params:
      model: openai/qwen3-vl:235b-instruct-cloud
      api_base: https://ollama.com/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: ollama-osmosis-osmosis-apply-1.7b
    litellm_params:
      model: ollama/Osmosis/Osmosis-Apply-1.7B
      api_base: http://10.89.34.87:11434/v1
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: openrouter-google-gemma-3-27b-it
    litellm_params:
      model: openrouter/google/gemma-3-27b-it:free
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: openrouter-kwaipilot-kat-coder-pro
    litellm_params:
      model: openrouter/kwaipilot/kat-coder-pro:free
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: openrouter-nvidia-nemotron-nano-12b-v2-vl
    litellm_params:
      model: openrouter/nvidia/nemotron-nano-12b-v2-vl:free
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: openrouter-openai-gpt-oss-20b
    litellm_params:
      model: openrouter/openai/gpt-oss-20b:free
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: openrouter-qwen-qwen3-coder
    litellm_params:
      model: openrouter/qwen/qwen3-coder
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: openrouter-qwen-qwen3-coder
    litellm_params:
      model: openrouter/qwen/qwen3-coder:free
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: openrouter-x-ai-grok-4.1-fast
    litellm_params:
      model: openrouter/x-ai/grok-4.1-fast:free
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: openrouter-z-ai-glm-4.5
    litellm_params:
      model: openrouter/z-ai/glm-4.5-air:free
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: qiniu-claude-4.5-haiku
    litellm_params:
      model: openai/claude-4.5-haiku
      api_base: https://api.qnaigc.com/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: qiniu-claude-4.5-sonnet
    litellm_params:
      model: openai/claude-4.5-sonnet
      api_base: https://api.qnaigc.com/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: siliconflow-BAAI-bge-m3
    litellm_params:
      model: siliconflow/BAAI/bge-m3
      api_base: https://api.siliconflow.cn/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: siliconflow-BAAI-bge-reranker-v2-m3
    litellm_params:
      model: siliconflow/BAAI/bge-reranker-v2-m3
      api_base: https://api.siliconflow.cn/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: siliconflow-deepseek-ai-deepseek-ocr
    litellm_params:
      model: siliconflow/deepseek-ai/DeepSeek-OCR
      api_base: https://api.siliconflow.cn/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: vercel-gemini-flash-latest
    litellm_params:
      model: openai/gemini-flash-latest
      api_base: https://openai-gemini-vercel-lake.vercel.app/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: vercel-gemini-flash-latest
    litellm_params:
      model: openai/gemini-flash-latest
      api_base: https://openai-gemini-vercel-lake.vercel.app/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: vercel-gemini-flash-lite-latest
    litellm_params:
      model: openai/gemini-flash-lite-latest
      api_base: https://openai-gemini-vercel-lake.vercel.app/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: vercel-gemini-flash-lite-latest
    litellm_params:
      model: openai/gemini-flash-lite-latest
      api_base: https://openai-gemini-vercel-lake.vercel.app/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: vercel-gemini-embedding
    litellm_params:
      model: openai/gemini-embedding-001
      api_base: https://openai-gemini-vercel-lake.vercel.app/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: vercel-gemini-pro-latest
    litellm_params:
      model: openai/gemini-pro-latest
      api_base: https://openai-gemini-vercel-lake.vercel.app/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True
  - model_name: volcengine-doubao-seed-code-preview-latest
    litellm_params:
      model: openai/doubao-seed-code-preview-latest
      api_base: https://ark.cn-beijing.volces.com/api/coding/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: False
  - model_name: zenmux-google-gemini-3-pro-preview-free
    litellm_params:
      model: openai/google/gemini-3-pro-preview-free
      api_base: https://zenmux.ai/api/v1
      api_key: YOUR_KEY
      api_version: "2025-04-21"
    model_info:
      supports_vision: True

router_settings:
  model_group_alias: {
    "claude-haiku-4.5": "qiniu-claude-4.5-haiku",
    "claude-sonnet-4.5": "qiniu-claude-4.5-sonnet",
  }
  num_retries: 100
